---
- name: update web, and nfs servers
  hosts: webservers, nfs, 
  become: yes
  tasks:
    - name: ensure wireshark is present
      yum:
        name: wireshark
        state: present

- name: update LB and db server
  hosts: lb, db
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is present 
      apt:
        name: wireshark
        state: present

